# Generated by Django 2.2.16 on 2022-12-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221209_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка для сообщения', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
